sonar.projectKey=sample-sps-devsecops-app
sonar.projectName=sample-sps-devsecops-app
sonar.sources=.
sonar.exclusions=node_modules/**,terraform/**,test/**
sonar.tests=test
sonar.test.inclusions=test/**/*.js